version: "2"
services:
  generator:
    build: ./app
    command: python generator.py
    container_name: "app"
    ports:
      - "8000:5000"
  
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - '6379'
  
  rq-worker:
    image: jaredv/rq-docker
    container_name: rq-worker
    command: rq worker --with-scheduler -u "redis://redis:6379"
    deploy:
      replicas: 1
    depends_on:
      - redis